//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Prilozhenie10
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// КартДоступ.
    /// </summary>
    // *** Start programmer edit section *** (КартДоступ CustomAttributes)

    // *** End programmer edit section *** (КартДоступ CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КартДоступE", new string[] {
            "СправСотр as \'Ответственный\'",
            "СправСотр.ФИОСтор as \'Ответственный\'"})]
    [View("КартДоступL", new string[] {
            "СправСотр.ФИОСтор as \'Ответственный\'"})]
    public class КартДоступ : ICSSoft.STORMNET.DataObject
    {
        
        private string fНомерКарт;
        
        private IIS.Prilozhenie10.СправСотр fСправСотр;
        
        private IIS.Prilozhenie10.DetailArrayOfТаблЧасть fТаблЧасть;
        
        // *** Start programmer edit section *** (КартДоступ CustomMembers)

        // *** End programmer edit section *** (КартДоступ CustomMembers)

        
        /// <summary>
        /// НомерКарт.
        /// </summary>
        // *** Start programmer edit section *** (КартДоступ.НомерКарт CustomAttributes)

        // *** End programmer edit section *** (КартДоступ.НомерКарт CustomAttributes)
        [StrLen(255)]
        public virtual string НомерКарт
        {
            get
            {
                // *** Start programmer edit section *** (КартДоступ.НомерКарт Get start)

                // *** End programmer edit section *** (КартДоступ.НомерКарт Get start)
                string result = this.fНомерКарт;
                // *** Start programmer edit section *** (КартДоступ.НомерКарт Get end)

                // *** End programmer edit section *** (КартДоступ.НомерКарт Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (КартДоступ.НомерКарт Set start)

                // *** End programmer edit section *** (КартДоступ.НомерКарт Set start)
                this.fНомерКарт = value;
                // *** Start programmer edit section *** (КартДоступ.НомерКарт Set end)

                // *** End programmer edit section *** (КартДоступ.НомерКарт Set end)
            }
        }
        
        /// <summary>
        /// КартДоступ.
        /// </summary>
        // *** Start programmer edit section *** (КартДоступ.СправСотр CustomAttributes)

        // *** End programmer edit section *** (КартДоступ.СправСотр CustomAttributes)
        [PropertyStorage(new string[] {
                "СправСотр"})]
        [NotNull()]
        public virtual IIS.Prilozhenie10.СправСотр СправСотр
        {
            get
            {
                // *** Start programmer edit section *** (КартДоступ.СправСотр Get start)

                // *** End programmer edit section *** (КартДоступ.СправСотр Get start)
                IIS.Prilozhenie10.СправСотр result = this.fСправСотр;
                // *** Start programmer edit section *** (КартДоступ.СправСотр Get end)

                // *** End programmer edit section *** (КартДоступ.СправСотр Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (КартДоступ.СправСотр Set start)

                // *** End programmer edit section *** (КартДоступ.СправСотр Set start)
                this.fСправСотр = value;
                // *** Start programmer edit section *** (КартДоступ.СправСотр Set end)

                // *** End programmer edit section *** (КартДоступ.СправСотр Set end)
            }
        }
        
        /// <summary>
        /// КартДоступ.
        /// </summary>
        // *** Start programmer edit section *** (КартДоступ.ТаблЧасть CustomAttributes)

        // *** End programmer edit section *** (КартДоступ.ТаблЧасть CustomAttributes)
        public virtual IIS.Prilozhenie10.DetailArrayOfТаблЧасть ТаблЧасть
        {
            get
            {
                // *** Start programmer edit section *** (КартДоступ.ТаблЧасть Get start)

                // *** End programmer edit section *** (КартДоступ.ТаблЧасть Get start)
                if ((this.fТаблЧасть == null))
                {
                    this.fТаблЧасть = new IIS.Prilozhenie10.DetailArrayOfТаблЧасть(this);
                }
                IIS.Prilozhenie10.DetailArrayOfТаблЧасть result = this.fТаблЧасть;
                // *** Start programmer edit section *** (КартДоступ.ТаблЧасть Get end)

                // *** End programmer edit section *** (КартДоступ.ТаблЧасть Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (КартДоступ.ТаблЧасть Set start)

                // *** End programmer edit section *** (КартДоступ.ТаблЧасть Set start)
                this.fТаблЧасть = value;
                // *** Start programmer edit section *** (КартДоступ.ТаблЧасть Set end)

                // *** End programmer edit section *** (КартДоступ.ТаблЧасть Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КартДоступE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КартДоступE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КартДоступE", typeof(IIS.Prilozhenie10.КартДоступ));
                }
            }
            
            /// <summary>
            /// "КартДоступL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КартДоступL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КартДоступL", typeof(IIS.Prilozhenie10.КартДоступ));
                }
            }
        }
    }
}
