//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Prilozhenie10
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// СправСотр.
    /// </summary>
    // *** Start programmer edit section *** (СправСотр CustomAttributes)

    // *** End programmer edit section *** (СправСотр CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СправСотрE", new string[] {
            "ФИОСтор as \'Сотрудник\'",
            "СправДол as \'Должность\'",
            "СправДол.Должность as \'Должность\'"})]
    [View("СправСотрL", new string[] {
            "ФИОСтор as \'Сотрудник\'",
            "СправДол.Должность as \'Должность\'"})]
    public class СправСотр : ICSSoft.STORMNET.DataObject
    {
        
        private string fФИОСтор;
        
        private IIS.Prilozhenie10.СправДол fСправДол;
        
        // *** Start programmer edit section *** (СправСотр CustomMembers)

        // *** End programmer edit section *** (СправСотр CustomMembers)

        
        /// <summary>
        /// ФИОСтор.
        /// </summary>
        // *** Start programmer edit section *** (СправСотр.ФИОСтор CustomAttributes)

        // *** End programmer edit section *** (СправСотр.ФИОСтор CustomAttributes)
        [StrLen(255)]
        public virtual string ФИОСтор
        {
            get
            {
                // *** Start programmer edit section *** (СправСотр.ФИОСтор Get start)

                // *** End programmer edit section *** (СправСотр.ФИОСтор Get start)
                string result = this.fФИОСтор;
                // *** Start programmer edit section *** (СправСотр.ФИОСтор Get end)

                // *** End programmer edit section *** (СправСотр.ФИОСтор Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СправСотр.ФИОСтор Set start)

                // *** End programmer edit section *** (СправСотр.ФИОСтор Set start)
                this.fФИОСтор = value;
                // *** Start programmer edit section *** (СправСотр.ФИОСтор Set end)

                // *** End programmer edit section *** (СправСотр.ФИОСтор Set end)
            }
        }
        
        /// <summary>
        /// СправСотр.
        /// </summary>
        // *** Start programmer edit section *** (СправСотр.СправДол CustomAttributes)

        // *** End programmer edit section *** (СправСотр.СправДол CustomAttributes)
        [PropertyStorage(new string[] {
                "СправДол"})]
        [NotNull()]
        public virtual IIS.Prilozhenie10.СправДол СправДол
        {
            get
            {
                // *** Start programmer edit section *** (СправСотр.СправДол Get start)

                // *** End programmer edit section *** (СправСотр.СправДол Get start)
                IIS.Prilozhenie10.СправДол result = this.fСправДол;
                // *** Start programmer edit section *** (СправСотр.СправДол Get end)

                // *** End programmer edit section *** (СправСотр.СправДол Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СправСотр.СправДол Set start)

                // *** End programmer edit section *** (СправСотр.СправДол Set start)
                this.fСправДол = value;
                // *** Start programmer edit section *** (СправСотр.СправДол Set end)

                // *** End programmer edit section *** (СправСотр.СправДол Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СправСотрE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СправСотрE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СправСотрE", typeof(IIS.Prilozhenie10.СправСотр));
                }
            }
            
            /// <summary>
            /// "СправСотрL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СправСотрL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СправСотрL", typeof(IIS.Prilozhenie10.СправСотр));
                }
            }
        }
    }
}
