//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Prilozhenie10
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// ТаблЧасть.
    /// </summary>
    // *** Start programmer edit section *** (ТаблЧасть CustomAttributes)

    // *** End programmer edit section *** (ТаблЧасть CustomAttributes)
    [AutoAltered()]
    [Caption("Табличная часть")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТаблЧастьE", new string[] {
            "НомКарт as \'Номер Карты\'"})]
    public class ТаблЧасть : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомКарт;
        
        private IIS.Prilozhenie10.КартДоступ fКартДоступ;
        
        // *** Start programmer edit section *** (ТаблЧасть CustomMembers)

        // *** End programmer edit section *** (ТаблЧасть CustomMembers)

        
        /// <summary>
        /// НомКарт.
        /// </summary>
        // *** Start programmer edit section *** (ТаблЧасть.НомКарт CustomAttributes)

        // *** End programmer edit section *** (ТаблЧасть.НомКарт CustomAttributes)
        public virtual int НомКарт
        {
            get
            {
                // *** Start programmer edit section *** (ТаблЧасть.НомКарт Get start)

                // *** End programmer edit section *** (ТаблЧасть.НомКарт Get start)
                int result = this.fНомКарт;
                // *** Start programmer edit section *** (ТаблЧасть.НомКарт Get end)

                // *** End programmer edit section *** (ТаблЧасть.НомКарт Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТаблЧасть.НомКарт Set start)

                // *** End programmer edit section *** (ТаблЧасть.НомКарт Set start)
                this.fНомКарт = value;
                // *** Start programmer edit section *** (ТаблЧасть.НомКарт Set end)

                // *** End programmer edit section *** (ТаблЧасть.НомКарт Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Prilozhenie10.КартДоступ.
        /// </summary>
        // *** Start programmer edit section *** (ТаблЧасть.КартДоступ CustomAttributes)

        // *** End programmer edit section *** (ТаблЧасть.КартДоступ CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "КартДоступ"})]
        public virtual IIS.Prilozhenie10.КартДоступ КартДоступ
        {
            get
            {
                // *** Start programmer edit section *** (ТаблЧасть.КартДоступ Get start)

                // *** End programmer edit section *** (ТаблЧасть.КартДоступ Get start)
                IIS.Prilozhenie10.КартДоступ result = this.fКартДоступ;
                // *** Start programmer edit section *** (ТаблЧасть.КартДоступ Get end)

                // *** End programmer edit section *** (ТаблЧасть.КартДоступ Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТаблЧасть.КартДоступ Set start)

                // *** End programmer edit section *** (ТаблЧасть.КартДоступ Set start)
                this.fКартДоступ = value;
                // *** Start programmer edit section *** (ТаблЧасть.КартДоступ Set end)

                // *** End programmer edit section *** (ТаблЧасть.КартДоступ Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТаблЧастьE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТаблЧастьE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТаблЧастьE", typeof(IIS.Prilozhenie10.ТаблЧасть));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ТаблЧасть.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfТаблЧасть CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfТаблЧасть CustomAttributes)
    public class DetailArrayOfТаблЧасть : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Prilozhenie10.DetailArrayOfТаблЧасть members)

        // *** End programmer edit section *** (IIS.Prilozhenie10.DetailArrayOfТаблЧасть members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ТаблЧасть by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ТаблЧасть.
        /// </summary>
        public DetailArrayOfТаблЧасть(IIS.Prilozhenie10.КартДоступ fКартДоступ) : 
                base(typeof(ТаблЧасть), ((ICSSoft.STORMNET.DataObject)(fКартДоступ)))
        {
        }
        
        public IIS.Prilozhenie10.ТаблЧасть this[int index]
        {
            get
            {
                return ((IIS.Prilozhenie10.ТаблЧасть)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Prilozhenie10.ТаблЧасть dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
